set shell := ['nu', '-c']
set positional-arguments

export package:="googleapis"

_default:
    @{{just_executable()}} -f {{justfile()}} --list --unsorted

# Create the package for Conan V2
build:
    rm -rf $env.package
    git clone --depth 1 --filter=blob:none --sparse https://github.com/googleapis/googleapis
    cd $env.package; git sparse-checkout set google/api; git sparse-checkout add google/rpc; \
    let date = ( git log -1 --format=%ad --date=format:'%Y%m%d' ); \
    let revision = ( git rev-parse HEAD | str substring 0..7 ); \
    let version = ( $date + "_" + $revision ); \
    /usr/bin/find [. ! "(" -name *.proto -or -name LICENSE ")" -delete ]; \
    cd ..; \
    echo "#!/bin/sh\n" | save export.sh -f; \
    echo ( "time conan export . --name " + $env.package + " --version " + $version ) | save export.sh --append -f;  \
    chmod u+x export.sh; \
    ./export.sh
