set shell := ['nu', '-c']
set positional-arguments

export package:="naturalsort"

_default:
    @{{just_executable()}} -f {{justfile()}} --list --unsorted

# Create the package for Conan V2
build:
    rm -rf $env.package
    git clone https://github.com/scopeInfinity/NaturalSort $env.package
    cd $env.package; \
    let date = ( git log -1 --format=%ad --date=format:'%Y%m%d' ); \
    let revision = ( git rev-parse HEAD | str substring 0..7 ); \
    let version = ( $date + "_" + $revision ); \
    /usr/bin/find [. ! "(" -name natural_sort.hpp -or -name LICENSE.md ")" -delete ]; \
    mv LICENSE.md $"($env.package)-license.txt"; \
    cd ..; \
    echo "#!/bin/sh\n" | save export.sh -f; \
    echo ( "time conan export . --name " + $env.package + " --version " + $version ) | save export.sh --append -f;  \
    chmod u+x export.sh; \
    ./export.sh
