set shell := ['nu', '-c']
set positional-arguments

export package:="dfxprotosweb"

_default:
    @{{just_executable()}} -f {{justfile()}} --list --unsorted

# Create the package for Conan V2
build:
    rm -rf include; \
    rm -rf protos; \
    rm -rf tmp; mkdir tmp; cd tmp; \
    git clone git@github.com:nuralogix/dfx-api.git; cd dfx-api; git checkout master; \
    cd ..; \
    cp dfx-api/lib/routes.json .; \
    rm -rf dfx-api; \
    git clone git@github.com:nuralogix/dfx-protos.git; cd dfx-protos; git checkout develop; \
    let date = ( git log -1 --format=%ad --date=format:'%Y%m%d' ); \
    let revision = ( git rev-parse HEAD | str substring 0..7 ); \
    let version = ( $date + "_" + $revision ); \
    cd ..; \
    cd ..; \
    mkdir protos/dfx; \
    cp -r tmp/dfx-protos/protos/public protos/dfx/proto; \
    rm -rf tmp/dfx-protos; \
    echo "#!/bin/sh\n" | save export.sh -f; \
    echo ( "time conan export . --name " + $env.package + " --version " + $version ) | save export.sh --append -f; \
    chmod u+x export.sh; \
    cp scripts/build_service_detail.py tmp/build_service_detail.py; \
    cd tmp; \
    ./build_service_detail.py; \
    cd ..; \
    mkdir include/dfx/api/web; \
    cp tmp/WebServiceDetail.hpp include/dfx/api/web/WebServiceDetail.hpp; \
    rm -rf tmp; \
    ./export.sh


